from .auth import auth_router
from .calls import call_router
from .rates import rate_router
from .cities import city_router
from .countries import country_router
from .customers import customer_router
from .categories import category_router
from .phone_numbers import phone_router
from .payments import payment_router
